package Presentation.views;

import Business.AuthResult;
import Presentation.controllers.AuthController;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.*;
import java.awt.event.*;
import java.io.InputStream;
import java.net.URL;

import Presentation.theme.AppColors;

public class LoginForm extends JPanel {

    public LoginForm(MainWindow mainWindow, AuthController auth, AuthPanel authPanel) {
        setLayout(new GridLayout(1,2));
        setOpaque(false);
        add(buildImagePanel(),BorderLayout.WEST);
        add(buildCenterPanel(mainWindow, auth, authPanel), BorderLayout.CENTER);
    }

    // ── Image background: background image with fallback ────────────────────────────
    // Uses background picture generated by gemini in this @Root Folder = /resources/image_login_1.jpg
    private JPanel buildImagePanel() {
        JPanel background = new JPanel() {

            private final Image background = loadBackground();  //Loaded once here — if the resource is missing, bg stays null
                                                                // and paintComponent falls back to the solid blue.
            private Image loadBackground() {
               URL url = getClass().getResource("/image_login_1.jpg");
                if (url == null) {
                    System.err.println("[LoginForm] Background image not found. " +
                            "Make sure the resources folder is marked as a Resources Root in IntelliJ.");
                    return null;
                }
                return new ImageIcon(url).getImage();
            }

            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                Graphics2D g2 = (Graphics2D) g.create();

                // Always paint a solid blue base first.
                // If the image loads, it sits on top at 50% opacity and the blue tints through.
                // If the image is missing, the panel is just solid blue.
                g2.setColor(AppColors.BRAND_MID);
                g2.fillRect(0, 0, getWidth(), getHeight());

                if (background != null) {
                    g2.setComposite(AlphaComposite.getInstance(AlphaComposite.SRC_OVER, 0.5f));
                    g2.drawImage(background, 0, 0, getWidth(), getHeight(), null);
                }

                g2.dispose();
            }
        };
        return background;
    }



    // ── Login Panel (Center) ──────────────────────────────────────────────────

    private JPanel buildCenterPanel(MainWindow mainWindow, AuthController auth, AuthPanel authPanel) {
        JPanel right = new JPanel(new GridBagLayout());
        right.setBackground(Color.WHITE);

        JPanel form = new JPanel();
        form.setBackground(Color.WHITE);
        form.setLayout(new BoxLayout(form, BoxLayout.Y_AXIS));
        form.setBorder(new EmptyBorder(10, 40, 10, 40));
        form.setMaximumSize(new Dimension(340, Integer.MAX_VALUE));

        JLabel title = new JLabel("LOGIN");
        title.setFont(new Font("SansSerif", Font.BOLD, 26));
        title.setForeground(AppColors.BRAND_DARK);
        title.setAlignmentX(Component.CENTER_ALIGNMENT);

        JLabel sub = new JLabel("LOGIN");
        sub.setFont(new Font("SansSerif", Font.PLAIN, 11));
        sub.setForeground(AppColors.TEXT_MUTED);
        sub.setAlignmentX(Component.CENTER_ALIGNMENT);

        JTextField     emailField = buildField("Email",    false);
        JPasswordField passField  = (JPasswordField) buildField("Password", true);

        JButton loginBtn = buildPrimaryButton("LOGIN");
        loginBtn.addActionListener(e -> {
            AuthResult result = auth.logIn(emailField.getText(), new String(passField.getPassword()));
            switch (result) {
                case SUCCESS -> {
                    mainWindow.getDashboard().refresh();
                    mainWindow.switchTo(MainWindow.DASHBOARD_SCREEN);
                    passField.setText("");

                }
                case EMPTY_FIELDS        -> JOptionPane.showMessageDialog(this, "Please fill all the fields!");
                case INVALID_CREDENTIALS -> {
                    JOptionPane.showMessageDialog(this, "Invalid credentials!");
                }
                case DATABASE_ERROR      -> JOptionPane.showMessageDialog(this, "Something went wrong, please try again!");
                default                  -> JOptionPane.showMessageDialog(this, "Something went wrong!");
            }
        });

        JLabel divider = new JLabel("── Or Sign up with ──");
        divider.setFont(new Font("SansSerif", Font.PLAIN, 11));
        divider.setForeground(AppColors.TEXT_MUTED);
        divider.setAlignmentX(Component.CENTER_ALIGNMENT);

        JLabel registerLink = new JLabel("Don't have an account? Register");
        registerLink.setFont(new Font("SansSerif", Font.PLAIN, 11));
        registerLink.setForeground(AppColors.BRAND_MID);
        registerLink.setCursor(new Cursor(Cursor.HAND_CURSOR));
        registerLink.setAlignmentX(Component.CENTER_ALIGNMENT);
        registerLink.addMouseListener(new MouseAdapter() {
            @Override public void mouseClicked(MouseEvent e) { authPanel.showRegister(mainWindow, auth); }
        });

        form.add(title);
        form.add(Box.createVerticalStrut(2));
        form.add(sub);
        form.add(Box.createVerticalStrut(22));
        form.add(emailField);
        form.add(Box.createVerticalStrut(12));
        form.add(passField);
        form.add(Box.createVerticalStrut(6));
        form.add(loginBtn);
        form.add(Box.createVerticalStrut(20));
        form.add(divider);
        form.add(Box.createVerticalStrut(10));
        form.add(registerLink);

        right.add(form);
        return right;
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private JTextField buildField(String placeholder, boolean isPassword) {
        JTextField field = isPassword ? new JPasswordField(20) : new JTextField(20);
        field.setFont(new Font("SansSerif", Font.PLAIN, 13));
        field.setForeground(new Color(60, 60, 70));
        field.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createMatteBorder(0, 0, 2, 0, AppColors.FIELD_BORDER),
                new EmptyBorder(8, 4, 8, 4)
        ));
        field.setMaximumSize(new Dimension(Integer.MAX_VALUE, 42));
        field.setAlignmentX(Component.CENTER_ALIGNMENT);

        if (!isPassword) {
            field.setForeground(AppColors.TEXT_MUTED);
            field.setText(placeholder);
            field.addFocusListener(new FocusAdapter() {
                @Override public void focusGained(FocusEvent e) {
                    if (field.getText().equals(placeholder)) { field.setText(""); field.setForeground(new Color(60,60,70)); }
                }
                @Override public void focusLost(FocusEvent e) {
                    if (field.getText().isBlank()) { field.setForeground(AppColors.TEXT_MUTED); field.setText(placeholder); }
                }
            });
        }
        return field;
    }

    private JButton buildPrimaryButton(String text) {
        JButton btn = new JButton(text);

        // Set standard colors using your theme palette
        btn.setBackground(AppColors.ACCENT);
        btn.setForeground(Color.WHITE);

        // Fonts and Layout
        btn.setFont(new Font("SansSerif", Font.BOLD, 13));
        btn.setMaximumSize(new Dimension(Integer.MAX_VALUE, 42));
        btn.setAlignmentX(Component.CENTER_ALIGNMENT);

        // Behaviors and Focus styling
        btn.setFocusPainted(false);
        btn.setCursor(new Cursor(Cursor.HAND_CURSOR));

        return btn;
    }
}